services:
  db:
    image: postgres:17.5-alpine3.21
    container_name: alta-db
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - altametrics

volumes:
  pgdata:

networks:
  altametrics: