services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    command: npm run preview -- --port 80 --host

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://nestuser:nestpass@db:5432/nestdb
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm run start:prod



volumes:
  pgdata: